<?php
/*
 You may not change or alter any portion of this comment or credits
 of supporting developers from this source code or any supporting source code
 which is considered copyrighted (c) material of the original comment or credit authors.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
/**
 * Xhttperror module
 *
 * @copyright       The XOOPS Project http://sourceforge.net/projects/xoops/
 * @license         GNU GPL 2 or later (http://www.gnu.org/licenses/gpl-2.0.html)
 * @package         xhttperror
 * @since           1.00
 * @author          Xoops Development Team
 * @version         svn:$id$
 */

defined('XOOPS_ROOT_PATH') || die('XOOPS root path not defined');

$modversion['name']             = _MI_XHTTPERROR_NAME;
$modversion['version']          = '1.01';
$modversion['description']      = _MI_XHTTPERROR_DESC;
$modversion['author']           = 'Rota Lucio';
$modversion['credits']          = 'Andrew Mills <a href"=emailto:ajmills@sirium.net">ajmillsATsiriumDOTnet</a>';
$modversion['help']             = 'page=help';
$modversion['license']          = 'GNU GPL 2.0 or later';
$modversion['license_url']      = "http://www.gnu.org/licenses/gpl-2.0.html";
$modversion['image']            = "assets/images/module_logo.png"; // Path and name of the module’s logo
$modversion['dirname']          = basename(dirname(__FILE__));
$modversion['dirmoduleadmin']   = 'Frameworks/moduleclasses';
$modversion['icons16']          = "modules/{$modversion['dirname']}/assets/images/icons/16x16";
$modversion['icons32']          = "modules/{$modversion['dirname']}/assets/images/icons/32x32";

$modversion['official']         = false;

include_once XOOPS_ROOT_PATH . '/modules/' . $modversion['dirname'] . '/include/constants.php';

// About
$modversion['module_status']        = 'RC1';
$modversion['release_date']         = '2014/11/26'; // YYYY/mm/dd
$modversion['module_website_url']   = 'http://www.xoops.org/';
$modversion['module_website_name']  = 'XOOPS';
$modversion['min_php']              = '5.3.7';
$modversion['min_xoops']            = '2.5.7.1';
$modversion['min_admin']            = '1.1';
$modversion['min_db']               = array(
    'mysql'  => '5.0.7',
    'mysqli' => '5.0.7'
);

$modversion['author_mail'] = 'lucio.rota@gmail.com';
$modversion['author_website_url'] = 'http://luciorota.altervista.org';
$modversion['author_website_name'] = 'http://luciorota.altervista.org';



// Install, update, unistall
$modversion['onInstall'] = 'include/oninstall.php';
$modversion['onUpdate'] = 'include/onupdate.php';
$modversion['onUninstall'] = 'include/onuninstall.php';



// Help files
$i                                     = 0;
$modversion['helpsection'][$i]['name'] = _MI_XHTTPERROR_HELP_HELP;
$modversion['helpsection'][$i]['link'] = "page=help";
++$i;
$modversion['helpsection'][$i]['name'] = _MI_XHTTPERROR_HELP_EXTRA_INFO;
$modversion['helpsection'][$i]['link'] = "page=extra_info";




// Admin things
$modversion['hasAdmin'] = true;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';
// If you want your module has a sub menu in system menu set it to 1
$modversion['system_menu'] = true;



// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
// Tables created by sql file (without prefix!)
$i                        = 0;
$modversion['tables'][$i] = $modversion['dirname'] . '_errors';
++$i;
$modversion['tables'][$i] = $modversion['dirname'] . '_reports';



// Search
$modversion['hasSearch'] = false;



// Menu
$modversion['hasMain'] = false;



// Blocks



// Templates
$i                                          = 0;
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_index.tpl';
$modversion['templates'][$i]['description'] = '';
// Admin templates
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_admin_errors_list.tpl';
$modversion['templates'][$i]['type']        = 'admin';
$modversion['templates'][$i]['description'] = '';
++$i;
$modversion['templates'][$i]['file']        = $modversion['dirname'] . '_admin_reports_list.tpl';
$modversion['templates'][$i]['type']        = 'admin';
$modversion['templates'][$i]['description'] = '';



// Module config setting
$i = 0;
++$i;
xoops_load('XoopsEditorHandler');
$editor_handler         = XoopsEditorHandler::getInstance();
$editorList             = array_flip($editor_handler->getList());

$modversion['config'][$i]['name']           = 'text_editor';
$modversion['config'][$i]['title']          = '_MI_XHTTPERROR_FORM_EDITOR';
$modversion['config'][$i]['description']    = '_MI_XHTTPERROR_FORM_EDITOR_DESC';
$modversion['config'][$i]['formtype']       = 'select';
$modversion['config'][$i]['valuetype']      = 'text';
$modversion['config'][$i]['default']        = 'dhtmltextarea';
$modversion['config'][$i]['options']        = XoopsLists::getDirListAsArray(XOOPS_ROOT_PATH . '/class/xoopseditor');
$modversion['config'][$i]['category']       = 'global';
// Ignore error reports for admins
++$i;
$modversion['config'][$i]['name']           = 'ignore_admin';
$modversion['config'][$i]['title']          = '_MI_XHTTPERROR_IGNOREADMIN';
$modversion['config'][$i]['description']    = '_MI_XHTTPERROR_IGNOREADMIN_DESC';
$modversion['config'][$i]['formtype']       = 'yesno';
$modversion['config'][$i]['valuetype']      = 'int';
$modversion['config'][$i]['default']        = true;
// Option to turn off error reporting
++$i;
$modversion['config'][$i]['name']           = 'error_reporting';
$modversion['config'][$i]['title']          = '_MI_XHTTPERROR_REPORTING';
$modversion['config'][$i]['description']    = '_MI_XHTTPERROR_REPORTING_DESC';
$modversion['config'][$i]['formtype']       = 'yesno';
$modversion['config'][$i]['valuetype']      = 'int';
$modversion['config'][$i]['default']        = false;
++$i;
// Show title in page title
$modversion['config'][$i]['name']           = 'title_as_page_title';
$modversion['config'][$i]['title']          = '_MI_XHTTPERROR_PAGETTL';
$modversion['config'][$i]['description']    = '_MI_XHTTPERROR_PAGETTL_DESC';
$modversion['config'][$i]['formtype']       = 'select';
$modversion['config'][$i]['valuetype']      = 'int';
$modversion['config'][$i]['default']        = '1';
$modversion['config'][$i]['options']        = array('_MI_XHTTPERROR_PAGETTL1' => '0', '_MI_XHTTPERROR_PAGETTL2' => '1', '_MI_XHTTPERROR_PAGETTL3' => '2');
// Reports per page
++$i;
$modversion['config'][$i]['name']           = 'reports_perpage';
$modversion['config'][$i]['title']          = '_MI_XHTTPERROR_NUMREPS';
$modversion['config'][$i]['description']    = '_MI_XHTTPERROR_NUMREPS_DESC';
$modversion['config'][$i]['formtype']       = 'textbox';
$modversion['config'][$i]['valuetype']      = 'int';
$modversion['config'][$i]['default']        = '50';



// Comments
$modversion['hasComments'] = false;



// Notifications
$modversion['hasNotification'] = false;
